### ISSUE TITLE
Building on the latest Rust

### ISSUE THREAD

**Issue by 56quarters** [tureus/whisper#1]
Hi there!

I came across this project while looking for a way to speed up my Graphite stack (the idea being to wrap a Rust or C implementation of Whisper with Python bindings). I noticed that it doesn't build with the most recent version of Rust. Would you like a PR to get it working with the most recent Rust version? Would a PR to also build a library target be alright? Thanks!

**Comment by xrl** [comment]
Yes! I would gladly accept that pull request!

**Comment by 56quarters** [comment]
Great, PR incoming in the next few days! Thank you!
